# Generated by Django 2.0.1 on 2018-08-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('accounts', '0003_auto_20180830_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jurisdictions',
            field=models.ManyToManyField(to='core.Jurisdiction'),
        ),
    ]
