# Generated by Django 2.0.1 on 2018-09-01 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_jurisdictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
