# Generated by Django 2.0.1 on 2018-09-01 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('accounts', '0005_auto_20180901_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJurisdictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.PositiveSmallIntegerField(choices=[(0, 'complete'), (1, 'basic'), (2, 'minimal')], default=2)),
            ],
            options={
                'verbose_name': 'Jurisdiction',
                'verbose_name_plural': 'Jurisdiction',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='jurisdictions',
        ),
        migrations.AddField(
            model_name='userjurisdictions',
            name='activist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjurisdictions',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Jurisdiction'),
        ),
        migrations.AlterUniqueTogether(
            name='userjurisdictions',
            unique_together={('jurisdiction', 'activist')},
        ),
    ]
