# Generated by Django 2.0.1 on 2018-08-28 23:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('core', '0004_auto_20171005_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=8)),
                ('last', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dx_City',
            fields=[
                ('city_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.CITIES_CITY_MODEL)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'DigiCity',
                'verbose_name_plural': 'DigiCities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='dx_County',
            fields=[
                ('county_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cities.Subregion')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'DigiCounty',
                'verbose_name_plural': 'DigiCounties',
                'ordering': ['county_name'],
            },
        ),
        migrations.CreateModel(
            name='dx_District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('district_type', models.CharField(max_length=32)),
                ('map_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/maps/districts/'), upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dex.dx_City')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dex.dx_County')),
            ],
            options={
                'verbose_name': 'Legislative District',
                'verbose_name_plural': 'Legislative Districts',
                'ordering': ['district_type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='dx_PostalCode',
            fields=[
                ('zip_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cities.PostalCode')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('state_leg_districts', models.ManyToManyField(to='dex.dx_District')),
            ],
            options={
                'verbose_name': 'dx_PostalCode',
                'verbose_name_plural': 'dx_PostalCodes',
                'ordering': ['zip_code'],
            },
        ),
        migrations.CreateModel(
            name='dx_State',
            fields=[
                ('state_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cities.Region')),
            ],
            options={
                'verbose_name': 'dx_State',
                'verbose_name_plural': 'dx_States',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='FBEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Organization')),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=8)),
                ('author', models.CharField(max_length=8)),
                ('link', models.CharField(max_length=128)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=64)),
                ('startdate', models.DateTimeField()),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=64)),
                ('participants', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'User Added Events',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dx_district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dex.dx_State'),
        ),
        migrations.AddField(
            model_name='dx_county',
            name='state_leg_districts',
            field=models.ManyToManyField(to='dex.dx_District'),
        ),
        migrations.AddField(
            model_name='dx_city',
            name='state_leg_districts',
            field=models.ManyToManyField(to='dex.dx_District'),
        ),
    ]
