# Generated by Django 2.0.1 on 2018-08-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizations', 'verbose_name_plural': 'Organization'},
        ),
    ]
